### ISSUE TITLE
[DG Review]

### ISSUE THREAD

**Issue by rafaelperes** [AY2021S2-CS2113T-F08-2/tp#285]
Good job folks, please find some comments to improve your DG. Specifically, you should also provide your diagrams.

1) As others have pointed out. The image related to architecture is missing

{width=”6.267716535433071in” height=”5.638888888888889in”}

2) Design. UML Class Diagram should be included to represent entities involved in your app.

3) Implementation. The details are well written. However, you should use a sequence diagram to represent the core aspect of app implementation.

4) "{.ul}"... This is a bit confusing. Maybe explain what does it stands for or fix it in case of a bug. Perhaps this is the same issue as to why images are not being displayed in your DG?

Let me know any issue ;)

**Comment by AlexanderTanJunAn** [comment]
Thanks for the input, we have worked on them already :)

**Comment by Chiamjiaen** [comment]
Thank you for your feedback. We have worked on the architecture diagram and the UML Class Diagrams have also been added. In addition, we have since also added sequence diagrams to at least one function in every feature.
